alias: "ENTSO-E v420: Robust Next-Day HTTP Update (13:50–20:50)"
description: >
  At 13:50, press the Force Next Day Update button to fetch tomorrow's prices.
  If that first attempt fails (e.g. ENTSO-E has not published yet or server
  issues), keep retrying every 30 minutes until 20:50, stopping early on
  success. Create persistent notifications and send error to mobile on final
  failure.
triggers:
  - trigger: time
    at: "13:50:00"
conditions: []
actions:
  - action: button.press
    target:
      entity_id: button.entso_e_test_entso_e_force_next_day_update
  - delay:
      minutes: 2
  - repeat:
      while:
        - condition: template
          value_template: >
            {{ not (states('sensor.entso_e_test_next_day_price_update_status')
            == 'SUCCESS'
                     and states('sensor.entso_e_test_next_day_current_price_status') == 'Valid') }}
        - condition: template
          value_template: >
            {% set now = now() %} {{ now.hour < 20 or (now.hour == 20 and
            now.minute <= 50) }}
      sequence:
        - delay:
            minutes: 30
        - choose:
            - conditions:
                - condition: template
                  value_template: >
                    {{ not
                    (states('sensor.entso_e_test_next_day_price_update_status')
                    == 'SUCCESS'
                             and states('sensor.entso_e_test_next_day_current_price_status') == 'Valid') }}
              sequence:
                - action: button.press
                  target:
                    entity_id: button.entso_e_test_entso_e_force_next_day_update
                - delay:
                    minutes: 2
  - choose:
      - conditions:
          - condition: template
            value_template: >
              {{ states('sensor.entso_e_test_next_day_price_update_status') ==
              'SUCCESS'
                 and states('sensor.entso_e_test_next_day_current_price_status') == 'Valid' }}
        sequence:
          - action: persistent_notification.create
            data:
              title: ENTSO-E Next-Day HTTP Success
              message: >
                Tomorrow's prices were updated successfully at some point
                between 13:50 and 20:50. Last tomorrow update time: {{
                states('sensor.entso_e_test_next_day_last_price_update_time') }}
              notification_id: entsoe_1350_status
      - conditions:
          - condition: template
            value_template: >
              {{ not (states('sensor.entso_e_test_next_day_price_update_status')
              == 'SUCCESS'
                       and states('sensor.entso_e_test_next_day_current_price_status') == 'Valid') }}
        sequence:
          - action: persistent_notification.create
            data:
              title: ENTSO-E Next-Day ERROR (after extended retries)
              message: >
                Failed to populate tomorrow's prices between 13:50 and 20:50,
                even after repeated HTTP retries. Status: {{
                states('sensor.entso_e_test_next_day_price_update_status') }}
                Current slot status: {{
                states('sensor.entso_e_test_next_day_current_price_status') }}
                Last tomorrow update time (if any): {{
                states('sensor.entso_e_test_next_day_last_price_update_time') }}
              notification_id: entsoe_1350_error
          - action: notify.mobile_app_sm_s911b
            data:
              title: ENTSO-E Next-Day ERROR (after extended retries)
              message: >
                Failed to populate tomorrow's prices between 13:50 and 20:50,
                even after repeated HTTP retries. Status: {{
                states('sensor.entso_e_test_next_day_price_update_status') }}
                Current slot status: {{
                states('sensor.entso_e_test_next_day_current_price_status') }}
                Last tomorrow update time (if any): {{
                states('sensor.entso_e_test_next_day_last_price_update_time') }}
mode: single
